apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    applicationId: "application-sleep0000"
    queue: "root.sandbox1"
  annotations:
    yunikorn.apache.org/user.info: "{\"user\": \"user1\", \"groups\": [\"group1\"]}"
  name: task0
spec:
  schedulerName: yunikorn
  restartPolicy: Never
  containers:
    - name: sleep-30s
      image: "alpine:latest"
      command: ["sleep", "300"]
      resources:
        requests:
          cpu: "1"
          memory: "1000M"
